language: go

go:
    - 1.8
    - tip

go_import_path: github.com/v3io/http_blaster
env:
  global:
    - VERSION=$(echo $TRAVIS_TAG)
before_deploy:
  - "GOOS=linux  GOARCH=amd64 go build -o http_blaster-${VERSION}-linux-amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o http_blaster-${VERSION}-darwin-amd64"
deploy:
    provider: releases
    api_key:
      secure: av7Ql1lnn0sJYOWRU3ITecK6IfUWBKK9MSCAUST9wPj/amC8Zo4ntZdbjBDufV9W1yFLFYnsSB7JUzy65Oz4GdZS5agcXMdwThS69/GzRphcClGGsf+g4tlwpI9W/f3qmRhlZDeazfB8cP0fPK7MHNiDHIT/pT+sfwccjAsAxmYlJsqXGkxpo/CZZ/VLgQA7L4WcwPQ+3/QyjfTjTVd2RnGiplK7I64PBJvxnFQWxHWYTEHD/aswcq57CnfklX0rmmu/d/4cUGWHWD7Ugodig0bMJSAcMiHcHpXylfVUXMdSLFQ8tIUxd7waNhQQOF0RyLOjequwf/uOOz+XsDAzc1c7BFoLSieRD9RBWb++Sz+b/5mevUHeB9uALN3v8pwbSEK7ZV54HmWd9BS3w3d4lUnOeQolysig4K+9hgKSsPZ/Vru7AcLqdlBo6Bb+ACRGhhKv+atm3VKKwpmE3aS+N9nRhPt4of5/rPu/7UI/wXDmTqDznCeFZS9sxgSyfj8gH10PWn7RMgNIFTQX+cAsqODiydbq3LiXoD60HVgG+jc2E9zrAjqwI/nZB2MCQFi4dnu3Atejc4OIZNthDL/9hglCs91C257JcXkG1R1tSPynCZC5klJ1wpGkD1Al4zhUVl267MDox+7LHrgW8G7S8cgSMz3FwfJ3ke4gzN5KzJ4=
    file:
      - "http_blaster-$VERSION-darwin-amd64"
      - "http_blaster-$VERSION-linux-amd64"
    skip_cleanup: true
    on:
        tags: true
