title = "Workload example"

[global]
block_size = 5
Duration = "160s"
server="192.168.206.10"
port="8081"
TLSMode=false
 [global.StatusCodesAcceptance]
  200 = 100.0 # upto 100% return status of 200
  204 = 100.0
  205 = 100.0

[workloads]
   [workloads.csv2kv_example]
   name="test csv2kv"
   Generator="csv2kv"
   bucket="1"
   Target="test_emd1/"
   Duration = "30s"
   TYPE="PUT"
   workers=10
   payload="examples/payloads/order-book-sample.csv"
   separator='|'
   schema="examples/schemas/schema_example.json"
   #KeyFormat="%v---%v._"
   KeyFields="Routing_Seq,Instrument_ID"
   #KeyFields="Routing_Seq"





