title = "Workload example"

[global]
block_size = 5
Duration = "160s"
server="192.168.206.10"
port="8081"
TLSMode=false
 [global.StatusCodesAcceptance]
  200 = 100.0 # upto 100% return status of 200
  204 = 100.0
  205 = 100.0

[workloads]
   [workloads.csv2kv_recursive_example]
   name="test csv2kv_example"
   Generator="csv2kv"
   bucket="1"
   Target="test_emd1/"
   Duration = "30s"
   TYPE="PUT"
   workers=10
   payload="examples/payloads/recursive"
   separator='|'
   schema="examples/schemas/order-book-sample.txt"
   KeyFormat="%v---%v._"
   KeyFields="Routing_Seq,Instrument_ID"






