title = "Workload example"

[global]
block_size = 5
Duration = "160s"
server="127.0.0.1"
port="8080"
TLSMode=false
 [global.StatusCodesAcceptance]
  200 = 100.0 # upto 100% return status of 200
  204 = 100.0
  205 = 100.0

[workloads]
   [workloads.get1]
   name="first"
   Generator="csv2kv"
   bucket=""
   file_path="test.html"
   Duration = "30s"
   TYPE="PUT"
   workers=20
   count=1
   payload="examples/payloads/order-book-sample.csv"
   separator='|'
   schema="examples/schemas/emd_schema_test.txt"





